service: azure-time-tracker

frameworkVersion: "2"

provider:
  name: azure
  region: westus2
  runtime: python3.8
  os: linux
  resourceGroup: time-tracker-wus2-dev-nodejs-functions-rg
  stage: dev
  functionApp:
    name: sls-time-tracker

  appInsights:
    name: sls-time-tracker-ai

  storageAccount:
    name: slstimetracker

plugins:
  - serverless-azure-functions

package:
  patterns:
    - "!env/**"
    - "!.env/**"
    - "!local.settings.json"
    - "!.vscode/**"
    - "!__pycache__/**"
    - "!node_modules/**"
    - "!.python_packages/**"
    - "!.funcignore"
    - "!package.json"
    - "!package-lock.json"
    - "!.gitignore"
    - "!.git/**"

functions:
  activities:
    handler: time_entries/application/azure_functions/activities.main
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: activities/{id:?}
          authLevel: anonymous
#  - ${file(activities/application/azure_functions/functions.yml)}
