service: azure-time-tracker

frameworkVersion: "2"

provider:
  name: azure
  region: westus2
  runtime: python3.8
  os: linux
  resourceGroup: time-tracker-wus2-dev-nodejs-functions-rg
  stage: dev
  functionApp:
    name: sls-time-tracker

  appInsights:
    name: sls-time-tracker-ai

  storageAccount:
    name: slstimetracker

plugins:
  - serverless-azure-functions

package:
  patterns:
    - "!env/**"
    - "!.env/**"
    - "!local.settings.json"
    - "!.vscode/**"
    - "!__pycache__/**"
    - "!node_modules/**"
    - "!.python_packages/**"
    - "!.funcignore"
    - "!package.json"
    - "!package-lock.json"
    - "!.gitignore"
    - "!.git/**"

functions:
  - ${file(azure_functions/activities/functions.yml)}
