version: '3.8'

services:
  api:
    container_name: "time-tracker-backend_api"
    build: 
        context: .
        dockerfile: ./Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes: 
      - .:/usr/src/app
    depends_on:
       - cosmosdb
    entrypoint:
      - /bin/sh
      - ./cosmosdb_emulator/entrypoint.sh

  cosmosdb:
    container_name: "azurecosmosemulator"
    hostname: "azurecosmosemulator"
    image: 'mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator'
    tty: true
    cpu_count: 2
    restart: always
    mem_limit: 3GB
    ports:
      - '8081:8081'
      - '10251:10251'
      - '10252:10252'
      - '10253:10253'
      - '10254:10254'
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=7
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_ARGS=/alternativenames=azurecosmosemulator