service: azure-time-tracker

frameworkVersion: "2"

provider:
  name: azure
  region: westus2
  runtime: python3.8
  os: linux
  resourceGroup: time-tracker-wus2-dev-nodejs-functions-rg
  stage: dev
  functionApp:
    name: sls-time-tracker

  appInsights:
    name: sls-time-tracker-ai

  storageAccount:
    name: slstimetracker

plugins:
  - serverless-azure-functions

package:
  patterns:
    - "!env/**"
    - "!.env/**"
    - "!local.settings.json"
    - "!.vscode/**"
    - "!__pycache__/**"
    - "!node_modules/**"
    - "!.python_packages/**"
    - "!.funcignore"
    - "!package.json"
    - "!package-lock.json"
    - "!.gitignore"
    - "!.git/**"

functions:
  get_activities:
    handler: time_tracker/activities/interface.get_activities
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: activities/{id:?}
          authLevel: anonymous

  delete_activity:
    handler: time_tracker/activities/interface.delete_activity
    events:
      - http: true
        x-azure-settings:
          methods:
            - DELETE
          route: activities/{id}
          authLevel: anonymous

  update_activity:
    handler: time_tracker/activities/interface.update_activity
    events:
      - http: true
        x-azure-settings:
          methods:
            - PUT   
          route: activities/{id}
          authLevel: anonymous    

  create_activity:
    handler: time_tracker/activities/interface.create_activity
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: activities/
          authLevel: anonymous

  create_time_entry:
    handler: time_tracker/time_entries/interface.create_time_entry
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: time-entries/
          authLevel: anonymous

  delete_time_entry:
    handler: time_tracker/time_entries/interface.delete_time_entry
    events:
      - http: true
        x-azure-settings:
          methods:
            - DELETE
          route: time-entries/{id}
          authLevel: anonymous
