service: azure-time-tracker

frameworkVersion: "2"

#region Config

provider:
  name: azure
  region: westus2
  runtime: python3.8
  os: linux
  resourceGroup: time-tracker-wus2-dev-nodejs-functions-rg
  stage: dev
  functionApp:
    name: sls-time-tracker

  appInsights:
    name: sls-time-tracker-ai

  storageAccount:
    name: slstimetracker

plugins:
  - serverless-azure-functions

package:
  patterns:
    - "!env/**"
    - "!.env/**"
    - "!local.settings.json"
    - "!.vscode/**"
    - "!__pycache__/**"
    - "!node_modules/**"
    - "!.python_packages/**"
    - "!.funcignore"
    - "!package.json"
    - "!package-lock.json"
    - "!.gitignore"
    - "!.git/**"

#endregion Fin Config

#region Functions

functions:

#region Activities

  get_activities:
    handler: time_tracker/activities/interface.get_activities
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: activities/{id:?}
          authLevel: anonymous

  delete_activity:
    handler: time_tracker/activities/interface.delete_activity
    events:
      - http: true
        x-azure-settings:
          methods:
            - DELETE
          route: activities/{id}
          authLevel: anonymous

  update_activity:
    handler: time_tracker/activities/interface.update_activity
    events:
      - http: true
        x-azure-settings:
          methods:
            - PUT   
          route: activities/{id}
          authLevel: anonymous    

  create_activity:
    handler: time_tracker/activities/interface.create_activity
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: activities/
          authLevel: anonymous

#endregion fin Activities

#region Time-Entries

  create_time_entry:
    handler: time_tracker/time_entries/interface.create_time_entry
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: time-entries/
          authLevel: anonymous

  delete_time_entry:
    handler: time_tracker/time_entries/interface.delete_time_entry
    events:
      - http: true
        x-azure-settings:
          methods:
            - DELETE
          route: time-entries/{id}
          authLevel: anonymous

#endregion Fin TimeEntries

#region Customer

  create_customer:
    handler: time_tracker/customers/interface.create_customer
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: customers/
          authLevel: anonymous

  get_customers:
    handler: time_tracker/customers/interface.get_customers
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: customers/{id:?}
          authLevel: anonymous

  update_customer:
    handler: time_tracker/customers/interface.update_customer
    events:
      - http: true
        x-azure-settings:
          methods:
            - PUT
          route: customers/{id}
          authLevel: anonymous

  delete_customer:
    handler: time_tracker/customers/interface.delete_customer
    events:
      - http: true
        x-azure-settings:
          methods:
            - DELETE
          route: customers/{id}
          authLevel: anonymous

#endregion Fin Customer

#endregion Fin Funciones
            
