name:  CI process for time-tracker-bk app

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - master
  #push:
    #branches: [ master ]

jobs:
  ci-test:
  name: Unit tests and linting
  runs-on: ubuntu-latest

  steps:
      - uses: actions/checkout@master
      - name: Initialize Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
      - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r V2/requirements.txt
      - name: Lint with flake8
      run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      #- name: Build binary wheel and a source tarball
      #run: python setup.py sdist
      # - name: Publish distribution to Test PyPI
      # uses: pypa/gh-action-pypi-publish@master
      # with:
      #     password: ${{ secrets.test_pypi_password }}
      #     repository_url: https://test.pypi.org/legacy/
